#!/bin/bash

# Fail loudly
set -euo pipefail
trap 'rc=$?;set +ex;if [[ $rc -ne 0 ]];then trap - ERR EXIT;echo 1>&2;echo "*** fail *** : code $rc : $DIR/$SCRIPT $ARGS" 1>&2;echo 1>&2;exit $rc;fi' ERR EXIT
ARGS="$*"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="$(basename "${BASH_SOURCE[0]}")"


timestamp=$(date '+%Y-%m-%d-%H%M-%S')
log_dir=${DIR}/run.logs
log_file=${log_dir}/run_${timestamp}.log


mkdir -p $log_dir

{
    set -x

    # NOTE: --userns=keep-id maps uid of user dusk (101) and gid of group duskadmin (1001)
    podman run \
           -it \
           --rm \
           -p 8000:8000 \
           --name duskies \
           duskies  "$@"

#           --mount type=bind,src=$(pwd),dst=/app \


} 2>&1 | tee $log_file
