#!/bin/bash

# Fail loudly
set -euo pipefail
trap 'rc=$?;set +ex;if [[ $rc -ne 0 ]];then trap - ERR EXIT;echo 1>&2;echo "*** fail *** : code $rc : $DIR/$SCRIPT $ARGS" 1>&2;echo 1>&2;exit $rc;fi' ERR EXIT
ARGS="$*"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="$(basename "${BASH_SOURCE[0]}")"


containerizer=${1:-${CONTAINERIZER:-podman}}

name_tag=lookout
echo name_tag: $name_tag

timestamp=$(date '+%Y-%m-%d-%H%M-%S')
log_dir=${DIR}/build.logs
log_file=${log_dir}/${name_tag}_${timestamp}.log

cd $DIR

touch force-rebuild-nonce

mkdir -p $log_dir

{
    set -x

    $containerizer build -f ${name_tag}.df -t ${name_tag} .
    $containerizer image tag ${name_tag} localhost/${name_tag}:latest

    set +x

} 2>&1 | tee $log_file
